#!/usr/bin/env python3
"""Generate the compiled-in copy of the 3DS Lua adapter.

The adapter normally lives on the SD card at Lua/3ds/platform.lua, which means
a stale SD-card deploy can leave a freshly built binary talking to an old (or
missing) adapter. On device that shows up as "3DS ADAPTER IS NOT ATTACHED" with
no further explanation.

Embedding the exact adapter that belongs to this binary removes that failure
class: the runtime prefers the SD copy, falls back to the embedded one, and
reports which of the two it used together with a CRC32 of the source, so the
two halves of a deploy can always be told apart.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "lua" / "3ds" / "platform.lua"
HEADER = ROOT / "src" / "3ds" / "embedded_platform_lua.hpp"

DELIMITER = "cth3ds_lua"

TEMPLATE = """// Generated by tools/embed_platform_lua.py. Do not edit by hand.
// Source: lua/3ds/platform.lua
#pragma once

namespace cth3ds {{

// Byte-for-byte copy of the adapter this binary was built with. Used when the
// SD card does not provide a loadable Lua/3ds/platform.lua.
inline constexpr char kEmbeddedPlatformLua[] = R"{delimiter}({body}){delimiter}";

}}  // namespace cth3ds
"""


def render(source_text: str) -> str:
    if f"){DELIMITER}\"" in source_text:
        raise SystemExit("adapter source contains the raw-string delimiter")
    return TEMPLATE.format(delimiter=DELIMITER, body=source_text)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated header is out of date instead of rewriting it",
    )
    args = parser.parse_args(argv)

    expected = render(SOURCE.read_text(encoding="utf-8"))
    if args.check:
        current = HEADER.read_text(encoding="utf-8") if HEADER.is_file() else ""
        if current != expected:
            print(
                "error: src/3ds/embedded_platform_lua.hpp is stale; "
                "run tools/embed_platform_lua.py",
                file=sys.stderr,
            )
            return 2
        print("embedded platform.lua is up to date")
        return 0

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
