#!/usr/bin/env python3
"""Reproduce the fixed startup/pause masks; never runs on the 3DS.

Usage: python3 tools/generate_presentation_masks.py --font FONT --output HEADER
Pillow, FreeType and the font SHA are recorded in the header.
The raster output contains only fixed phrases, no embedded font program.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, features, __version__
from fontTools.ttLib import TTFont

PHRASES = (
    ("loading", "载入中，请稍等……", 18),
    ("credit", "移植适配：uncodeuncle.com", 13),
    ("based", "Based on CorsixTH", 13),
    ("paused", "已暂停 · Start继续", 12),
    ("paused_build", "已暂停 · 可建造 · Start继续", 12),
    ("hint_keyboard_unavailable", "键盘不可用，请使用存档槽", 12),
    ("hint_digits_only", "此处只能输入数字", 12),
    ("hint_input_rejected", "输入内容不符合此项要求", 12),
    ("hint_resume_speed", "请先解除暂停，再调整速度", 12),
    ("hint_speed_unchanged", "游戏速度未改变", 12),
    ("hint_speed_1", "速度：最慢", 12),
    ("hint_speed_2", "速度：较慢", 12),
    ("hint_speed_3", "速度：正常", 12),
    ("hint_speed_4", "速度：最快", 12),
    ("hint_speed_5", "速度：再快一些", 12),
    ("hint_zoom_locked", "3DS 已固定游戏缩放比例", 12),
    ("hint_save_no_world", "请先开始或载入医院，再保存", 12),
    ("hint_place", "A 放置 · X 旋转 · B 取消", 12),
    ("hint_room", "拖动建房 · B 取消 · Y 墙体", 12),
    ("hint_keyboard", "A 打开键盘 · B 取消", 12),
    ("hint_wide", "广角 480×288 · L 切换清晰视野", 12),
    ("hint_clear", "清晰 400×240 · L 切换广角视野", 12),
    ("hint_target", "已显示目标，请再次按下", 12),
    ("hint_input_reset", "长时间停顿后已重置输入", 12),
)


def generate(font_path):
    cmap = TTFont(font_path).getBestCmap()
    missing = {ch for _, phrase, _ in PHRASES for ch in phrase if ord(ch) not in cmap}
    if missing:
        raise ValueError("Missing glyphs: " + "".join(sorted(missing)))
    lines = ["// Generated by tools/generate_presentation_masks.py; do not hand-edit.",
             "// Font SHA256: " + hashlib.sha256(Path(font_path).read_bytes()).hexdigest(),
             f"// Pillow {__version__}; FreeType {features.version('freetype2')}",
             "#pragma once", "#include <cstdint>", "namespace cth3ds::presentation_masks {",
             "struct Mask { int width, height; const std::uint8_t* data; };"]
    for name, phrase, size in PHRASES:
        font = ImageFont.truetype(str(font_path), size, layout_engine=ImageFont.Layout.BASIC)
        box = font.getbbox(phrase)
        width, height = box[2] - box[0], box[3] - box[1]
        image = Image.new("L", (width, height))
        ImageDraw.Draw(image).text((-box[0], -box[1]), phrase, font=font, fill=255)
        # Four-bit alpha preserves the small font's antialiasing in read-only data.
        pixels = [(value + 8) // 17 for value in image.getdata()]
        packed = [(pixels[i] << 4) | (pixels[i + 1] if i + 1 < len(pixels) else 0)
                  for i in range(0, len(pixels), 2)]
        lines += [f"// {phrase}; {size}px", f"inline constexpr std::uint8_t {name}_data[] = {{"]
        lines += ["  " + ",".join(f"0x{v:02x}" for v in packed[i:i+24]) + ","
                  for i in range(0, len(packed), 24)]
        lines += ["};", f"inline constexpr Mask {name}{{{width}, {height}, {name}_data}};"]
    return "\n".join(lines + ["} // namespace cth3ds::presentation_masks", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(generate(args.font))
