#!/usr/bin/env python3
"""Generate a verified CorsixTH 3DS source view from pinned CorsixTH 0.70.1.

AR3: --dry-run executes the complete pipeline in a temporary
view; --output publishes a new view link without changing source or overlay.
Production callers select this complete view under a single build owner.
Original Theme Hospital data belongs outside the supplied source checkout.
"""

from __future__ import annotations

from dual_screen_canvas import patch_dual_screen, check_dual_screen
from handheld_ui import patch_handheld_ui, check_handheld_ui
from load_recovery import patch_load_recovery, check_load_recovery
from pathlib import Path
from sound_callbacks import patch_sound_callbacks, check_sound_callbacks
from sound_lifetime import (sound_transaction, patch_sound_lifetime,
                            check_sound_lifetime, SoundPatchError)
from sprite_residency import patch_sprite_residency, check_sprite_residency
from typing import Iterable, Sequence
import argparse
import json
import sys
from integration.generated_view import SourceView, seal_view, verify_view, validate_output
from integration.common import (
    APP_ATTACH_MARKER,
    APP_BOOT_MARKER,
    APP_CONFIG_MARKER,
    APP_LEVEL_READY_MARKER,
    APP_LOG_SORT_MARKER,
    APP_PLAYER_NAME_MARKER,
    APP_STAGE_AUDIO_MARKER,
    APP_STAGE_DATA_MARKER,
    APP_STAGE_GFX_MARKER,
    APP_STAGE_HELPER_MARKER,
    APP_STAGE_INIT_MARKER,
    APP_STAGE_LANGUAGE_MARKER,
    APP_STAGE_LOADING_MARKER,
    APP_STAGE_UI_MARKER,
    APP_STAGE_VIDEO_MARKER,
    BOOTSTRAP_SURFACE_MARKER,
    BZIP2_CMAKE_MARKER,
    CMAKE_DATA_MARKER,
    Change,
    GFX_QUALITY_MARKER,
    GFX_REGISTER_MARKER,
    GFX_RENDERER_MARKER,
    GFX_WINDOW_MARKER,
    GFX_ZOOM_BUFFER_MARKER,
    IntegrationError,
    MAIN_INCLUDE_MARKER,
    MAIN_INIT_GUARD_MARKER,
    MAIN_REGISTER_MARKER,
    OVERLAY_VERSION,
    ROOT_CMAKE_MARKER,
    SDL_AFTER_FRAME_MARKER,
    SDL_CMAKE_MARKER,
    SDL_FILTER_MARKER,
    SDL_FRAME_STACK_MARKER,
    SDL_INCLUDE_MARKER,
    SDL_INIT_MARKER,
    SDL_MIXER_CMAKE_MARKER,
    SDL_SHUTDOWN_MARKER,
    SDL_TICK_MARKER,
    SRC_CMAKE_MARKER,
    UPSTREAM_COMMIT,
    UPSTREAM_TAG,
    append_block,
    read_text,
    replace_many,
    replace_once,
    sha256_file,
    write_text,
)
from integration.overlay import (
    copy_overlay,
    git_head,
    iter_overlay_files,
    manifest,
    refresh_embedded_adapter,
    validate_upstream,
)
from integration.source_patches import (
    patch_sources,
)
from integration.product_patches import (
    patch_product_sources,
    validate_product_upgrade,
)
from integration.sound_init import (
    SOUND_INIT_LEGACY,
    SOUND_INIT_MARKER,
    SOUND_INIT_R41_TRANSACTION,
    SOUND_INIT_TRANSACTION,
    patch_sound_initialization,
)
from integration.clock import (
    SIMULATION_CLOCK_SITES,
    patch_simulation_clock,
)
from integration.observations import (
    patch_u3_observations,
)
from integration.validation import (
    check_integrated,
)
from integration.render_fast import patch_render_fast
from integration.render_gpu import patch_render_gpu
from integration.cpu_hotspots import patch_cpu_hotspots
from integration.media import patch_media


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("upstream", type=Path, help="CorsixTH source checkout or release archive")
    parser.add_argument(
        "--overlay-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="corsixth-3ds-port root (normally inferred)",
    )
    parser.add_argument("--check", action="store_true", help="verify an already integrated tree")
    parser.add_argument("--dry-run", action="store_true", help="generate and fully verify in a disposable view")
    parser.add_argument("--output", type=Path, help="publish a new source-view link; existing paths are never replaced")
    parser.add_argument("--private-output", type=Path, help="fill a new or owned empty real directory for an isolated verifier")
    parser.add_argument(
        "--allow-unverified",
        action="store_true",
        help="allow a non-pinned compatible fork; integration anchors still must match",
    )
    parser.add_argument("--json", action="store_true", help="emit machine-readable output")
    return parser


def generate_complete(root: Path, overlay: Path, provenance: str) -> list[Change]:
    """One real pipeline for both preflight and explicit publication.

    The caller owns disposable root and overlay. Per-transform dry-run branches
    are never used: every later transform sees all preceding generated bytes.
    """
    validate_product_upgrade(root)
    changes = copy_overlay(root, overlay, False)
    changes.extend(patch_sources(root, False))
    changes.extend(patch_product_sources(root, False))
    changes.extend(patch_sound_initialization(root))
    changes.extend(Change(path, "sound-lifetime") for path in
                   patch_sound_lifetime(root, SOUND_INIT_R41_TRANSACTION))
    changes.extend(Change(path, "load-recovery") for path in patch_load_recovery(root))
    changes.extend(patch_u3_observations(root, False))
    changes.extend(patch_simulation_clock(root))
    changes.extend(Change(path, "sound-callbacks") for path in patch_sound_callbacks(root))
    changes.extend(Change(path, "sprite-residency") for path in patch_sprite_residency(root))
    changes.extend(Change(path, "dual-screen-canvas") for path in patch_dual_screen(root))
    changes.extend(Change(path, "handheld-ui") for path in patch_handheld_ui(root))
    changes.extend(Change(path, "render-fast") for path in patch_render_fast(root))
    changes.extend(Change(path, "render-gpu") for path in patch_render_gpu(root))
    changes.extend(Change(path, "cpu-hotspots") for path in patch_cpu_hotspots(root, overlay))
    changes.extend(Change(path, "media") for path in patch_media(root))
    from integration.runner_adapter import patch_runner_adapter
    changes.extend(patch_runner_adapter(root))
    integrated_manifest = manifest(root, overlay, provenance)
    manifest_path = root / "CorsixTH/Src/3ds/integration-manifest.json"
    manifest_text = json.dumps(integrated_manifest, indent=2, sort_keys=True) + "\n"
    if not manifest_path.is_file() or read_text(manifest_path) != manifest_text:
        write_text(manifest_path, manifest_text, False)
        changes.append(Change(manifest_path.relative_to(root).as_posix(), "generate"))
    errors = check_integrated(root, overlay)
    if errors:
        raise IntegrationError("post-integration verification failed: " + "; ".join(errors))
    return changes


def reject_partial_input(root: Path, overlay: Path, provenance: str) -> None:
    """Accept clean source or this complete generation, never replay old trees.

    Version-specific migration remains a separate follow-up. Current generated
    trees that differ from the selected overlay require a clean pinned input.
    """
    manifest_path = root / 'CorsixTH/Src/3ds/integration-manifest.json'
    if manifest_path.is_file():
        verify_view(root)
        errors = check_integrated(root, overlay)
        if errors or json.loads(read_text(manifest_path)) != manifest(root, overlay, provenance):
            raise IntegrationError('input is not this complete generation; use clean pinned upstream')
        return
    if (root / 'CorsixTH/Src/3ds').exists() or (root / 'CorsixTH/Lua/3ds').exists():
        raise IntegrationError('partial generated input; use clean pinned upstream')
    for path in root.rglob('*'):
        if path.is_file() and path.suffix in ('.lua', '.cpp', '.h', '.txt', '.cmake'):
            if 'CORSIXTH_3DS' in read_text(path):
                raise IntegrationError('unmanifested generated input; use clean pinned upstream')


def generation_provenance(root: Path, validated: str) -> str:
    """Retain a verified generation's origin after .git is deliberately omitted.

    A generated view has source-signature validation, not live Git validation.
    Only the known pinned Git origin can be retained from its manifest; the
    complete manifest and generated checks are validated before it is used.
    Payloads separately report validation_provenance to keep this distinction.
    """
    path = root / 'CorsixTH/Src/3ds/integration-manifest.json'
    if validated == 'source-signature:v0.70.1' and path.is_file():
        stored = json.loads(read_text(path))
        if not isinstance(stored, dict):
            raise IntegrationError('generated manifest must be a JSON object')
        if (stored.get('upstream_commit') == UPSTREAM_COMMIT and
                stored.get('upstream_tag') == UPSTREAM_TAG and
                stored.get('provenance') == 'git:' + UPSTREAM_COMMIT):
            return stored['provenance']
    return validated


def generate_private(source: Path, overlay: Path, output: Path) -> dict:
    """Fresh verifier only: fill a new or caller-owned empty real directory.

    Existing nonempty roots and links are refused. An allocated empty authority
    root retains its inode. No output contents are written before full validation.
    """
    import shutil
    output = output.absolute()
    allocated = output.exists()
    allocated_identity = (output.stat().st_dev, output.stat().st_ino) if allocated else None
    if source.is_symlink() or overlay.is_symlink():
        raise IntegrationError("private generation requires real roots, without source or output links")
    output = output.parent.resolve() / output.name
    source, overlay = source.resolve(), overlay.resolve()
    validate_output(output, source, overlay, private_empty=True)
    validated = validate_upstream(source, False)
    validate_product_upgrade(source)
    provenance = generation_provenance(source, validated)
    with SourceView(source, overlay, None) as view:
        reject_partial_input(view.root, view.private_overlay, provenance)
        generate_complete(view.root, view.private_overlay, provenance)
        receipt = seal_view(view.root, overlay, provenance)
        view.verify_inputs()
        if validate_upstream(source, False) != validated:
            raise IntegrationError("upstream identity changed during generation")
        # copytree creates the exclusive private root. Failure never touches a
        # prior tree; callers retain this new failed workspace for diagnostics.
        validate_output(output, source, overlay, private_empty=True)
        if allocated and (output.stat().st_dev, output.stat().st_ino) != allocated_identity:
            raise IntegrationError("private output root identity changed during generation")
        shutil.copytree(view.root, output, dirs_exist_ok=allocated)
        verify_view(output, overlay)
    return receipt


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.upstream.expanduser().resolve()
    overlay = args.overlay_root.expanduser().resolve()
    try:
        if args.check and (args.dry_run or args.output or args.private_output):
            raise IntegrationError('--check cannot be combined with generation options')
        if args.private_output and (args.output or args.dry_run):
            raise IntegrationError('--private-output is an exclusive real-root generation mode')
        if args.private_output:
            receipt = generate_private(args.upstream.expanduser().absolute(),
                                       args.overlay_root.expanduser().absolute(), args.private_output)
            print(json.dumps({"ok": True, "mode": "private",
                              "view_sha256": receipt["view_sha256"],
                              "output": str(args.private_output)}, sort_keys=True))
            return 0
        if not args.check and not args.dry_run and args.output is None:
            raise IntegrationError('in-place publication is disabled; '
                                   'use --output NEW_VIEW and build that view')
        output = None
        if args.output is not None:
            candidate = args.output.expanduser().absolute()
            output = candidate.parent.resolve() / candidate.name
        validation_provenance = validate_upstream(root, args.allow_unverified)
        validate_product_upgrade(root)
        provenance = generation_provenance(root, validation_provenance)
        if args.check:
            with SourceView(root, overlay, None) as view:
                verify_view(view.root, overlay)
                errors = check_integrated(view.root, view.private_overlay)
                if not errors:
                    reject_partial_input(view.root, view.private_overlay, provenance)
                view.verify_inputs()
                if validate_upstream(root, args.allow_unverified) != validation_provenance:
                    raise IntegrationError('upstream identity changed during check')
            payload = {
                "ok": not errors,
                "mode": "check",
                "upstream": str(root),
                "provenance": provenance,
                "validation_provenance": validation_provenance,
                "errors": errors,
            }
            if args.json:
                print(json.dumps(payload, indent=2, sort_keys=True))
            elif errors:
                for error in errors:
                    print(f"error: {error}", file=sys.stderr)
            else:
                print(f"CorsixTH 3DS integration verified: {root}")
            return 0 if not errors else 2

        with SourceView(root, overlay, output) as view:
            reject_partial_input(view.root, view.private_overlay, provenance)
            changes = generate_complete(view.root, view.private_overlay, provenance)
            receipt = seal_view(view.root, overlay, provenance)
            view.verify_inputs()
            if validate_upstream(root, args.allow_unverified) != validation_provenance:
                raise IntegrationError('upstream identity changed during generation')
            if not args.dry_run:
                view.publish()

        payload = {
            "ok": True,
            "mode": "dry-run" if args.dry_run else "integrate",
            "upstream": str(root),
            "provenance": provenance,
            "validation_provenance": validation_provenance,
            "output": str(output) if output and not args.dry_run else None,
            "publication": "new-source-view-link" if not args.dry_run else "none",
            "view_sha256": receipt["view_sha256"],
            "changes": [change.__dict__ for change in changes],
        }
        if args.json:
            print(json.dumps(payload, indent=2, sort_keys=True))
        else:
            action = "Verified" if args.dry_run else "Published"
            print(f"{action} {len(changes)} changes from {root}" +
                  (f" at {output}" if not args.dry_run else " (input unchanged)"))
            for change in changes:
                print(f"  {change.operation:8s} {change.path}")
        return 0
    except (IntegrationError, SoundPatchError, ValueError, OSError) as exc:
        if args.json:
            print(json.dumps({"ok": False, "error": str(exc)}, indent=2, sort_keys=True))
        else:
            print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
